### ISSUE TITLE
AOSP 12 bootlooping after flashing the build.

### ISSUE THREAD

**Issue by mdsohail99** [sonyxperiadev/device-sony-griffin#17]
Hi, first of all thank you so much for making clear instructions for AOSP 12 build. I am getting bootloop after flashing the build. I followed exact guidelines as instructed. Can you please tell me what could have gone wrong. Thanks.

**Comment by jerpelea** [comment]
please cherry-pick this workaround 
https://github.com/sonyxperiadev/device-sony-common/pull/871
