### ISSUE TITLE
Xperia 1 Sony Open Devices

### ISSUE THREAD

**Issue by aret1nol** [sonyxperiadev/device-sony-griffin#5]
Hello! I'm from Russia. I would like to buy a sony xperia 1. I want to modify the standard firmware and for this I need to unlock the bootloader.
Unlocking the bootloader, as I understand it, is not possible on all models. How do I determine before a purchase in a store that a specific phone can unlock the bootloader?
Is it possible to unlock the bootloader on all sony xperia 1 or 5 phones that are sold in Russia?
Can I expect that the new sony xperia models that will be released in 2020 will also be added to the Sony Open Devices program?
The links that I used:
https://developer.sony.com/posts/xperia-1-added-to-sonys-open-devices-program/
https://developer.sony.com/develop/open-devices/get-started/unlock-bootloader/

**Comment by Haxk20** [comment]
Sadly this is a hard to talk about. You newer know if it will be unlockable. But the best option is devices bought outside of operator. Those are almost 100% unlockable. With operator devices its well luck based game. Some are unlockable some are not.

As to what devices that are added to this program. All Qcom SoC devices are added.
